Customizing page titles for book reports

diff --git a/_tests/check-seo-metadata b/_tests/check-seo-metadata
--- a/_tests/check-seo-metadata
+++ b/_tests/check-seo-metadata
@@ -24,3 +24,9 @@ if ! egrep '"og:title".*="Notes from PyGotham 2019"' _site/retrospectives/pygoth
   echo "ERROR: Non-monthly retrospective has incorrect title";
   exit 1;
 fi
+
+
+if ! egrep '"og:title".*="Book Report: Happy City by Charles Montgomery"' _site/book-reports/happy-city/index.html; then
+  echo "ERROR: Book report does not have expected opengraph title";
+  exit 1;
+fi
